### ISSUE TITLE
Erro no importação mysql

### ISSUE THREAD

**Issue by braganetx** [lucasfacchini/open-data-cnpj-import#1]
python3 mysql_import.py localhost 3306 <user> <pass> <database>
(INFO): Creating schema
(INFO): Ran script schema/mysql/drop-tables.sql
(INFO): Ran script schema/mysql/create-tables.sql
(INFO): Analyzing files
(INFO): Found 37 files
(INFO): Truncating tables
(INFO): Importing file data/motivo_situacao_cadastral.csv - 1 of 37
  0%|                                                    | 0/68 [00:00<?, ?it/s](INFO): Importing file data/output-extract/K3241.K03200Y0.D10410.EMPRECSV - 2 of 37
100%|███████████████████████████████████████████| 68/68 [14:31<00:00, 12.81s/it]
Traceback (most recent call last):█▉| 5013001/5032255 [14:31<00:03, 5323.61it/s]
  File "mysql_import.py", line 54, in <module>
    sql.run(parser)
  File "/mnt/hgfs/DADOS_BR/cnpj/parser/importer.py", line 38, in run
    self.cursor.executemany(self.build_insert(parser, keys), lines)
  File "/home/braga/.local/lib/python3.8/site-packages/mysql/connector/cursor.py", line 670, in executemany
    return self.execute(stmt)
  File "/home/braga/.local/lib/python3.8/site-packages/mysql/connector/cursor.py", line 568, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/braga/.local/lib/python3.8/site-packages/mysql/connector/connection.py", line 686, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/braga/.local/lib/python3.8/site-packages/mysql/connector/connection.py", line 573, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1366 (HY000): Incorrect integer value: '' for column 'porte' at row 1
100%|██████████████████████████████▉| 5014000/5032255 [14:31<00:03, 5751.96it/s]

Quando está chegando 100% na primeira importação está ocorrendo esse erro, como se tivesse tentando inserir um tipo errado na coluna porte.

Saberia como posso corrigir

**Comment by lucasfacchini** [comment]
Olá @braganetx, isso nāo chegou a acontecer nos meus testes, mas irei refazer os mesmos para verificar.
Acredito que possa ser alguma linha que possua dados incorretos no arquivo, por isso peço que verifique se há algo sugestivo nas ultimas linhas do arquivo.
Se nāo for isso, daria para testar fazendo algum ajuste na classe CnpjCsvParser, para preencher a informaçāo com zero nesse caso.

Assim que possível farei uns testes para tentar tratar essas situaçōes.

**Comment by lucasfacchini** [comment]
Olá @braganetx, fiz novos testes e identifiquei que o erro que você reportou realmente acontecia.
Parece que os arquivos da receita possuem a coluna referente ao porte da empresa vazia em alguns casos.
Fiz a correção neste commit: https://github.com/lucasfacchini/open-data-cnpj-import/commit/76d92cc8ee52afe31547a76659a8b7cae9f94e2a
