### ISSUE TITLE
Erro ao executar

### ISSUE THREAD

**Issue by ricardoambrico** [lucasfacchini/open-data-cnpj-import#2]
Olá Lucas blz?
sou novo na área de programação e estou aprendo PHP juntamente com MySQL porém seu codigo está em python, instalei o python na minha maquina e baixei os arquivos do seu projeto, ao executar pelo prompt do DOS, mostra a seguinte mensagem.

E:\open-data-cnpj-import-master>python mysql_import.py localhost 3307 root epiz_23247280_consulta
Traceback (most recent call last):
  File "E:\dados_receita\open-data-cnpj-import-master\mysql_import.py", line 3, in <module>
    from parser.parsers import generate_parsers_from_files, EstabeleCsvParser
ModuleNotFoundError: No module named 'parser.parsers'; 'parser' is not a package

*meu bd nao possui senha e seu nome é epiz_23247280_consulta. Utilizo o XAMPP. 
agradeço desde já!

**Comment by lucasfacchini** [comment]
Olá Ricardo,

Esse erro realmente não era algo que deveria acontecer. Peço que verifique se você extraiu todos arquivos e pastas contidos aqui no repositório. Pois a única possibilidade de acontecer esse erro é se você não possui a pasta parser com os arquivos dentro. Para conferir isso você pode acessar a pasta no explorador de arquivo, ou usar o comando `dir` (se estiver no Windows).
Quando a conexão, no momento você precisaria setar uma senha para o seu usuário root no SGBD. Pois a implementação que captura os dados do comando espera que você insira uma senha. No entanto, vou colocar como um TODO futuro para melhorar essa questão, para que a senha seja opcional.

**Comment by ricardoambrico** [comment]
todos os arquivos estão corretos. Até baixei novamente, acho q pode ser no arquivo "parsers.py" Parece nao encontrar o pacote parser. Executei todos os arquivos dentro da pasta parser e o unico que dá erro é o "parsers.py" 

>parsers.py
Traceback (most recent call last):
  File "E:\open-data-cnpj-import-master\parser\parsers.py", line 1, in <module>
    from parser.utils import *
ModuleNotFoundError: No module named 'parser.utils'; 'parser' is not a package

e quando coloco
>pip install parser
ERROR: Could not find a version that satisfies the requirement parser (from versions: none)
ERROR: No matching distribution found for parser

mas vou pesquisar mais e aprender um pouco mais... 
obs.: fiz o pip install parse e instalou porem ainda nao funciona.
vlwww

**Comment by lucasfacchini** [comment]
Oi Ricardo, a execução individual dos arquivos realmente vai causar erro por causa da forma com que os pacotes são importados.
Mas o pacote `parser` não é algo que tu precise instalar, pois se refere aos componentes dentro da pasta parser.
Se descobrir o que pode ser, peço que nos avise por aqui, até porque pode ser algo com a forma que estou usando os pacotes no código.
