### ISSUE TITLE
Importação do arquivo SIMPLES

### ISSUE THREAD

**Issue by jonatarodri** [lucasfacchini/open-data-cnpj-import#4]
Olá!

Estou recebendo este retorno na tentativa de importar o arquivo do SIMPLES (F.K03200$W.SIMPLES.CSV.D10710) disponibilizado no dia 19/07/2021.

(ERROR): 1292 (22007): Incorrect date value: '0000-00-00' for column 'simei_inicio' at row 1
(ERROR): 1292 (22007): Incorrect date value: '0000-00-00' for column 'simples_fim' at row 1

O erro se repete para todos os registros do arquivo do SIMPLES.

@lucasfacchini alguma sugestão?

**Comment by lucasfacchini** [comment]
Olá @jonatarodri, realizei um ajuste para tratar essa questão no commit https://github.com/lucasfacchini/open-data-cnpj-import/commit/9af3cf811e5c0e94cacb86a6e8b2670a1ad0e299.
Peço que atualize o código em seu ambiente, e tente realizar a importação.
Caso queira ignorar arquivos já importados, você pode comentar os parsers na função [generate_parsers_from_files](https://github.com/lucasfacchini/open-data-cnpj-import/blob/master/parser/parsers.py).
