### ISSUE TITLE
Erro na execução do container

### ISSUE THREAD

**Issue by henriquemeca** [lucasfacchini/open-data-cnpj-import#6]
Após criar o container em docker e tentar rodar o script mysql_import.py o script dá erro de autenticação ->'caching_sha2_password' is not supported.

Para remover esse erro é preciso incluir na criação do container o default-authentication-plugin:

docker run --name mysql-cnpj -p 3306:3306 -h localhost -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=cnpj -d mysql --default-authentication-plugin=mysql_native_password

Dessa forma o script conseguiu funcionar

**Comment by lucasfacchini** [comment]
Olá, realizei um teste aqui e não consegui simular o erro, considerando a criação de um novo container, conforme consta no README.
Mas acredito que isso possa ser a versão do pacote `mysql-connector-python` que você possui instalado.
![image](https://user-images.githubusercontent.com/4080698/148832697-0d24a563-6f1f-45fb-9581-2f00609912ff.png)
Verifique se você possui esse pacote com esse nome e em qual versão está.
Caso esteja em uma versão antiga, ou não possui o pacote, peço que atualize/instale e tente novamente.
Vale olhar também se pode ser o problema descrito nessa questão: https://stackoverflow.com/a/53561512
